-- Superseded by supabase/events_policies.sql.
--
-- The old version of this file added permissive event-manager policies on top
-- of existing event policies. Because permissive RLS policies are OR'd
-- together, event access must be rebuilt in one consolidated policy set.
-- Run supabase/events_policies.sql for the current event authorization model.
